version: '3.6'

networks:
  service04:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442
services:
  app:
    build: .
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    volumes:
      - data:/mnt
    environment:
      DB: /mnt/db.sqlite
      PORT: 5000
    networks:
      - service04
volumes:
  data:
